Fix typo in docker buildx push
Broke `tags`, resulting in:

```
tag is needed when pushing to registry
Error: The process '/usr/bin/docker' failed with exit code 1
```